# Generated by Django 5.2 on 2025-05-08 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_full_name', models.CharField(max_length=100)),
                ('shopping_email', models.CharField(max_length=100)),
                ('shopping_address1', models.CharField(blank=True, max_length=250)),
                ('shopping_address2', models.CharField(blank=True, max_length=250, null=True)),
                ('shopping_city', models.CharField(blank=True, max_length=25)),
                ('shopping_state', models.CharField(blank=True, max_length=25)),
                ('shopping_zipcode', models.CharField(blank=True, max_length=25)),
                ('shopping_country', models.CharField(default='IRAN', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
