# Generated by Django 5.2 on 2025-05-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
