# Generated by Django 5.2 on 2025-04-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_mojodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mojodi',
            new_name='available',
        ),
    ]
